version: '3.8'

services:
  web:
    build: .
    image: romanki/flask-test-app:latest
    command: python main.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres-postgresql
  postgres-postgresql:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0ssw0rd
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
